// Mocks generated by Mockito 5.0.10 from annotations
// in mobichan/test/features/board/data/repositories/board_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mobichan/features/board/data/data_sources/board_local_data_source.dart'
    as _i5;
import 'package:mobichan/features/board/data/data_sources/board_remote_data_source.dart'
    as _i3;
import 'package:mobichan/features/board/data/models/board_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeBoardModel extends _i1.Fake implements _i2.BoardModel {}

/// A class which mocks [BoardRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoardRemoteDataSource extends _i1.Mock
    implements _i3.BoardRemoteDataSource {
  MockBoardRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.BoardModel>> getAllBoards() => (super.noSuchMethod(
          Invocation.method(#getAllBoards, []),
          returnValue: Future<List<_i2.BoardModel>>.value(<_i2.BoardModel>[]))
      as _i4.Future<List<_i2.BoardModel>>);
  @override
  _i4.Future<_i2.BoardModel> getBoard(String? code) =>
      (super.noSuchMethod(Invocation.method(#getBoard, [code]),
              returnValue: Future<_i2.BoardModel>.value(_FakeBoardModel()))
          as _i4.Future<_i2.BoardModel>);
}

/// A class which mocks [BoardLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoardLocalDataSource extends _i1.Mock
    implements _i5.BoardLocalDataSource {
  MockBoardLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BoardModel> getLastBoard() =>
      (super.noSuchMethod(Invocation.method(#getLastBoard, []),
              returnValue: Future<_i2.BoardModel>.value(_FakeBoardModel()))
          as _i4.Future<_i2.BoardModel>);
  @override
  _i4.Future<void> cacheBoard(_i2.BoardModel? boardToCache) =>
      (super.noSuchMethod(Invocation.method(#cacheBoard, [boardToCache]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i4.Future<void>);
}
