// Mocks generated by Mockito 5.0.10 from annotations
// in mobichan/test/features/board/domain/use_cases/get_board_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mobichan/core/error/failure.dart' as _i5;
import 'package:mobichan/features/board/domain/entities/board.dart' as _i6;
import 'package:mobichan/features/board/domain/repositories/board_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {
  @override
  String toString() => super.toString();
}

/// A class which mocks [BoardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBoardRepository extends _i1.Mock implements _i3.BoardRepository {
  MockBoardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Board>>> getAllBoards() =>
      (super.noSuchMethod(Invocation.method(#getAllBoards, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Board>>>.value(
              _FakeEither<_i5.Failure, List<_i6.Board>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.Board>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Board>> getBoard(String? code) =>
      (super.noSuchMethod(Invocation.method(#getBoard, [code]),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.Board>>.value(
                  _FakeEither<_i5.Failure, _i6.Board>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Board>>);
}
