name: mobichan
description: A 4chan app made with Flutter.
publish_to: 'none'
version: 1.3.1+15

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_inappwebview: ^5.3.2
  http: ^0.13.3
  shared_preferences: ^2.0.6
  flutter_html: ^2.1.0
  dio: ^4.0.0
  image_picker: ^0.8.1
  cached_network_image: ^3.0.0
  html_unescape: ^2.0.0
  video_player: ^2.1.6
  image_gallery_saver: ^1.6.9
  permission_handler: ^8.1.2
  path_provider: ^2.0.2
  flutter_vlc_player: ^6.0.2
  package_info_plus: ^1.0.3
  flutter_displaymode: ^0.3.2
  version: ^2.0.0
  photo_view: ^0.11.1
  install_plugin:
    git:
      url: https://github.com/mitchross/flutter_install_plugin.git
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/settings.json
    - assets/
    - files/
