name: mobichan
description: A 4chan app made with Flutter.
publish_to: 'none'
version: 1.3.5+19

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.8
  flutter_html: ^2.2.0
  dio: ^4.0.1
  image_picker: ^0.8.4+4
  cached_network_image: ^3.1.0
  html_unescape: ^2.0.0
  video_player: ^2.2.6
  image_gallery_saver: ^1.7.1
  permission_handler: ^8.2.5
  path_provider: ^2.0.6
  flutter_vlc_player: ^6.0.5
  package_info_plus: ^1.3.0
  flutter_displaymode: ^0.3.2
  version: ^2.0.0
  photo_view: ^0.13.0
  install_plugin:
    git:
      url: https://github.com/mitchross/flutter_install_plugin.git
  url_launcher: ^6.0.12
  screenshot: ^1.2.3
  share: ^2.0.4
  easy_localization: ^3.0.0
  html: ^0.15.0
  connectivity_plus: ^1.4.0
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  mobichan_domain:
    path: packages/mobichan_domain
  mobichan_data:
    path: packages/mobichan_data
  configurable_expansion_tile_null_safety: ^2.0.0
  shimmer: ^2.0.0
  get_it: ^7.2.0
  firebase_core: ^1.10.0
  firebase_crashlytics: ^2.3.0
  scrollable_positioned_list: ^0.2.3
  string_similarity: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  cider: ^0.1.0
  build_runner: ^2.1.4
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/
