name: 'Generate Auto Changelog'
on:
  push:
    branches:
      - develop
jobs:
  master:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Generate Auto Changelog
        uses: ardalanamini/auto-changelog@v1.1.0
        id: generate-changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print changelog
        run: echo "The changelog is ${{ steps.generate-changelog.output.changelog }}"
