name: Validate Pull Request
on:
  pull_request_target:
    branches:
      - develop
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Decoding android/key.properties
        run: echo "${{ secrets.KEYPROP }}" | base64 --decode > android/key.properties

      - name: Decoding android/app/upload-keystore.jks
        run: echo "${{ secrets.KEYJKS }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Pub Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --split-per-abi --release

      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: PR-apk
          path: ./build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk