name: Validate Feature Branch
on:
  push:
    branches:
      - feature/**
jobs:
  build:
    name: Build Appbundle and Apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Decoding android/key.properties
        run: echo "${{ secrets.KEYPROP }}" | base64 --decode > android/key.properties

      - name: Decoding android/app/upload-keystore.jks
        run: echo "${{ secrets.KEYJKS }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Pub Get Packages
        run: flutter pub get

      - name: Running domain layer tests
        run: flutter test packages/mobichan_domain

      - name: Running data layer tests
        run: flutter test packages/mobichan_data

      - name: Running presentation layer tests
        run: flutter test

      - name: Build app bundle
        run: flutter build appbundle

      - name: Build apk
        run: flutter build apk --split-per-abi --release

      - name: Upload app bundle
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

  publish:
    name: Publish to Play Store
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v1

      - name: Get appbundle from artifacts
        uses: actions/download-artifact@v2
        with:
          name: appbundle

      - name: Release app to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.lucasgoudin.mobichan
          releaseFiles: app-release.aab
          track: internal